// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: reciever/reciever.proto

package reciever

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GraphDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GraphDataRequest) Reset() {
	*x = GraphDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reciever_reciever_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GraphDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphDataRequest) ProtoMessage() {}

func (x *GraphDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reciever_reciever_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphDataRequest.ProtoReflect.Descriptor instead.
func (*GraphDataRequest) Descriptor() ([]byte, []int) {
	return file_reciever_reciever_proto_rawDescGZIP(), []int{0}
}

func (x *GraphDataRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type GraphDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *GraphDataResponse) Reset() {
	*x = GraphDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reciever_reciever_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GraphDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphDataResponse) ProtoMessage() {}

func (x *GraphDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reciever_reciever_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphDataResponse.ProtoReflect.Descriptor instead.
func (*GraphDataResponse) Descriptor() ([]byte, []int) {
	return file_reciever_reciever_proto_rawDescGZIP(), []int{1}
}

func (x *GraphDataResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GraphData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Data   string `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Status int64  `protobuf:"varint,3,opt,name=Status,proto3" json:"Status,omitempty"`
}

func (x *GraphData) Reset() {
	*x = GraphData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reciever_reciever_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GraphData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphData) ProtoMessage() {}

func (x *GraphData) ProtoReflect() protoreflect.Message {
	mi := &file_reciever_reciever_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphData.ProtoReflect.Descriptor instead.
func (*GraphData) Descriptor() ([]byte, []int) {
	return file_reciever_reciever_proto_rawDescGZIP(), []int{2}
}

func (x *GraphData) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GraphData) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *GraphData) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_reciever_reciever_proto protoreflect.FileDescriptor

var file_reciever_reciever_proto_rawDesc = []byte{
	0x0a, 0x17, 0x72, 0x65, 0x63, 0x69, 0x65, 0x76, 0x65, 0x72, 0x2f, 0x72, 0x65, 0x63, 0x69, 0x65,
	0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x68, 0x65, 0x6c, 0x6c, 0x6f,
	0x77, 0x6f, 0x72, 0x6c, 0x64, 0x22, 0x26, 0x0a, 0x10, 0x47, 0x72, 0x61, 0x70, 0x68, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x2d, 0x0a,
	0x11, 0x47, 0x72, 0x61, 0x70, 0x68, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x47, 0x0a, 0x09,
	0x47, 0x72, 0x61, 0x70, 0x68, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a,
	0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0x51, 0x0a, 0x08, 0x52, 0x65, 0x63, 0x69, 0x65, 0x76, 0x65,
	0x72, 0x12, 0x45, 0x0a, 0x04, 0x53, 0x65, 0x6e, 0x64, 0x12, 0x1c, 0x2e, 0x68, 0x65, 0x6c, 0x6c,
	0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x47, 0x72, 0x61, 0x70, 0x68, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77,
	0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x47, 0x72, 0x61, 0x70, 0x68, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x16, 0x5a, 0x14, 0x67, 0x72, 0x61, 0x70,
	0x68, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65, 0x63, 0x69, 0x65, 0x76, 0x65, 0x72,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_reciever_reciever_proto_rawDescOnce sync.Once
	file_reciever_reciever_proto_rawDescData = file_reciever_reciever_proto_rawDesc
)

func file_reciever_reciever_proto_rawDescGZIP() []byte {
	file_reciever_reciever_proto_rawDescOnce.Do(func() {
		file_reciever_reciever_proto_rawDescData = protoimpl.X.CompressGZIP(file_reciever_reciever_proto_rawDescData)
	})
	return file_reciever_reciever_proto_rawDescData
}

var file_reciever_reciever_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_reciever_reciever_proto_goTypes = []interface{}{
	(*GraphDataRequest)(nil),  // 0: helloworld.GraphDataRequest
	(*GraphDataResponse)(nil), // 1: helloworld.GraphDataResponse
	(*GraphData)(nil),         // 2: helloworld.GraphData
}
var file_reciever_reciever_proto_depIdxs = []int32{
	0, // 0: helloworld.Reciever.Send:input_type -> helloworld.GraphDataRequest
	1, // 1: helloworld.Reciever.Send:output_type -> helloworld.GraphDataResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_reciever_reciever_proto_init() }
func file_reciever_reciever_proto_init() {
	if File_reciever_reciever_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_reciever_reciever_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GraphDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reciever_reciever_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GraphDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reciever_reciever_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GraphData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_reciever_reciever_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_reciever_reciever_proto_goTypes,
		DependencyIndexes: file_reciever_reciever_proto_depIdxs,
		MessageInfos:      file_reciever_reciever_proto_msgTypes,
	}.Build()
	File_reciever_reciever_proto = out.File
	file_reciever_reciever_proto_rawDesc = nil
	file_reciever_reciever_proto_goTypes = nil
	file_reciever_reciever_proto_depIdxs = nil
}
