// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: reciever/reciever.proto

package reciever

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RecieverClient is the client API for Reciever service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RecieverClient interface {
	Send(ctx context.Context, in *GraphDataRequest, opts ...grpc.CallOption) (*GraphDataResponse, error)
}

type recieverClient struct {
	cc grpc.ClientConnInterface
}

func NewRecieverClient(cc grpc.ClientConnInterface) RecieverClient {
	return &recieverClient{cc}
}

func (c *recieverClient) Send(ctx context.Context, in *GraphDataRequest, opts ...grpc.CallOption) (*GraphDataResponse, error) {
	out := new(GraphDataResponse)
	err := c.cc.Invoke(ctx, "/helloworld.Reciever/Send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecieverServer is the server API for Reciever service.
// All implementations must embed UnimplementedRecieverServer
// for forward compatibility
type RecieverServer interface {
	Send(context.Context, *GraphDataRequest) (*GraphDataResponse, error)
	mustEmbedUnimplementedRecieverServer()
}

// UnimplementedRecieverServer must be embedded to have forward compatible implementations.
type UnimplementedRecieverServer struct {
}

func (UnimplementedRecieverServer) Send(context.Context, *GraphDataRequest) (*GraphDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedRecieverServer) mustEmbedUnimplementedRecieverServer() {}

// UnsafeRecieverServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecieverServer will
// result in compilation errors.
type UnsafeRecieverServer interface {
	mustEmbedUnimplementedRecieverServer()
}

func RegisterRecieverServer(s grpc.ServiceRegistrar, srv RecieverServer) {
	s.RegisterService(&Reciever_ServiceDesc, srv)
}

func _Reciever_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GraphDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecieverServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Reciever/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecieverServer).Send(ctx, req.(*GraphDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Reciever_ServiceDesc is the grpc.ServiceDesc for Reciever service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Reciever_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.Reciever",
	HandlerType: (*RecieverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _Reciever_Send_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "reciever/reciever.proto",
}
